// Code generated by protoc-gen-go. DO NOT EDIT.
// source: discoverable_service_transport.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DiscoverableServiceTransport struct {
	Address              string   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscoverableServiceTransport) Reset()         { *m = DiscoverableServiceTransport{} }
func (m *DiscoverableServiceTransport) String() string { return proto.CompactTextString(m) }
func (*DiscoverableServiceTransport) ProtoMessage()    {}
func (*DiscoverableServiceTransport) Descriptor() ([]byte, []int) {
	return fileDescriptor_79f5d63db4e673bc, []int{0}
}

func (m *DiscoverableServiceTransport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoverableServiceTransport.Unmarshal(m, b)
}
func (m *DiscoverableServiceTransport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoverableServiceTransport.Marshal(b, m, deterministic)
}
func (m *DiscoverableServiceTransport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoverableServiceTransport.Merge(m, src)
}
func (m *DiscoverableServiceTransport) XXX_Size() int {
	return xxx_messageInfo_DiscoverableServiceTransport.Size(m)
}
func (m *DiscoverableServiceTransport) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoverableServiceTransport.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoverableServiceTransport proto.InternalMessageInfo

func (m *DiscoverableServiceTransport) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*DiscoverableServiceTransport)(nil), "pb.DiscoverableServiceTransport")
}

func init() {
	proto.RegisterFile("discoverable_service_transport.proto", fileDescriptor_79f5d63db4e673bc)
}

var fileDescriptor_79f5d63db4e673bc = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x52, 0x49, 0xc9, 0x2c, 0x4e,
	0xce, 0x2f, 0x4b, 0x2d, 0x4a, 0x4c, 0xca, 0x49, 0x8d, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e,
	0x8d, 0x2f, 0x29, 0x4a, 0xcc, 0x2b, 0x2e, 0xc8, 0x2f, 0x2a, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x2a, 0x48, 0x52, 0xb2, 0xe0, 0x92, 0x71, 0x41, 0x52, 0x1b, 0x0c, 0x51, 0x1a, 0x02,
	0x53, 0x29, 0x24, 0xc1, 0xc5, 0xee, 0x98, 0x92, 0x52, 0x94, 0x5a, 0x5c, 0x2c, 0xc1, 0xa8, 0xc0,
	0xa8, 0xc1, 0x19, 0x04, 0xe3, 0x26, 0xb1, 0x81, 0x0d, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0xd4, 0x14, 0x59, 0x18, 0x6c, 0x00, 0x00, 0x00,
}
